In [19]:
import numpy as np

In [3]:
list1 = [1 , 2, 3, 4]
list2 = [[1, 2, 3, 4]]
list3 = [[1, 2, 3, 4], [10, 20, 30, 40], [100, 200, 300, 400]]
arr1 = np.array(list1)
arr2 = np.array(list2)
arr3 = np.array(list3)
print(type(arr1), type(arr2), type(arr3))

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [4]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(4,)
(1, 4)
(3, 4)


In [5]:
arr4 = np.linspace(0, 10, 5)
print(arr4)

[ 0.   2.5  5.   7.5 10. ]


In [6]:
print(arr1[2])

3


In [7]:
arr4 = np.array([[1, 2, 3, 4], [10, 20, 30, 40], [100, 200, 300, 400]])

In [17]:
print(arr4[0:2, 2:4])

[[ 3  4]
 [30 40]]


In [24]:
arr5 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reshaped_array = arr5.reshape((4,2))
print(arr5)
print(reshaped_array)

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [31]:
arr6 = np.array([1, 2, 3, 4, 5])
reshaped_array6 = arr6.reshape(1, -1)
print(reshaped_array6)

[[1 2 3 4 5]]
