In [1]:
import numpy as np

In [3]:
arr1 = np.array([[1, 2], [3, 4], [5, 6]])
arr2 = np.array([[7, 8]])
combined_array = np.concatenate((arr1, arr2))
print(combined_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
arr3 = np.array([[9], [10], [11], [12]])
combined_array1 = np.concatenate((combined_array, arr3), axis=1)
print(combined_array1)

[[ 1  2  9]
 [ 3  4 10]
 [ 5  6 11]
 [ 7  8 12]]


In [7]:
arr4 = np.array([1, 2, 3, 4, 5, 6])
reshaped1 = arr4.reshape((2, -1))
print(reshaped1)

[[1 2 3]
 [4 5 6]]


In [9]:
reshaped2 = np.reshape(arr4, (2, -1))
print(reshaped2)

[[1 2 3]
 [4 5 6]]
